export enum AuthErrors {
  EMAIL_EXISTS = "EMAIL_EXISTS",
  OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED",
  TOO_MANY_ATTEMPTS_TRY_LATER = "TOO_MANY_ATTEMPTS_TRY_LATER",
  EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  USER_DISABLED = "USER_DISABLED"
}

